require "spec_helper"
require "fileutils"
require "tmpdir"
require "git"

RSpec.describe Cimas::Cli::Command do
  context "commit message must include request-checks" do
    it "add request-checks: true if missing" do
      command = Cimas::Cli::Command.new(options("Some commit message"))

      expect(command.commit_message).to eq("Some commit message\n\nrequest-checks: true")
    end

    it "don't modify message if request-checks: is passed" do
      command = Cimas::Cli::Command.new(options("Some commit message\n\nrequest-checks: false"))

      expect(command.commit_message).to eq("Some commit message\n\nrequest-checks: false")
    end
  end

  describe "apply_patches" do
    let(:tmp_root) { Dir.mktmpdir("cimas-patches-spec") }
    let(:repo_name) { "metanorma-cli" }
    let(:repo_dir) { File.join(tmp_root, repo_name) }
    let(:gemspec_path) { File.join(repo_dir, "foo.gemspec") }
    let(:git_repo) { Git.init(repo_dir) }

    before do
      FileUtils.mkdir_p(repo_dir)
      File.write(gemspec_path, <<~GEMSPEC)
        Gem::Specification.new do |spec|
          spec.name = "foo"
          spec.required_ruby_version = Gem::Requirement.new(">= 2.7.0")
        end
      GEMSPEC
    end

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(patches_block)
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(
        "repositories" => {
          repo_name => {
            "remote" => "ssh://git@github.com/metanorma/#{repo_name}",
            "branch" => "main",
            "files" => {},
          },
        },
        "groups" => {
          "processor" => [repo_name],
        },
        "patches" => patches_block,
      ))

      Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
      )
    end

    it "rewrites matching lines without prepending the auto-generated header" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["processor"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_repo)
      content = File.read(gemspec_path)

      expect(content).to include('>= 3.1.0')
      expect(content).not_to include('>= 2.7.0')
      expect(content).not_to include('Auto-generated by Cimas')
    end

    it "stages the patched file in the git index under its repo-relative path" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["processor"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_repo)

      # ls-files = the index itself (status.* compares against HEAD, which a
      # freshly-init'd repo does not have).
      expect(git_repo.ls_files).to include("foo.gemspec")
    end

    it "warns and leaves the file untouched when the find pattern does not match" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'this_will_never_match',
          "replace" => 'irrelevant',
          "groups" => ["processor"],
        },
      )

      expect { command.apply_patches(repo_name, repo_dir, git_repo) }
        .to output(/pattern not present in file/).to_stdout

      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end

    it "warns when the glob matches no files" do
      command = build_command(
        "nonexistent" => {
          "files" => ["*.nope"],
          "find" => 'foo',
          "replace" => 'bar',
          "groups" => ["processor"],
        },
      )

      expect { command.apply_patches(repo_name, repo_dir, git_repo) }
        .to output(/no files matched glob/).to_stdout
    end

    it "skips repos that are not in any of the patch's groups" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["model"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_repo)
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end

    it "does not write the file in dry-run mode" do
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(
        "repositories" => {
          repo_name => {
            "remote" => "ssh://git@github.com/metanorma/#{repo_name}",
            "branch" => "main",
            "files" => {},
          },
        },
        "groups" => { "processor" => [repo_name] },
        "patches" => {
          "ruby_version" => {
            "files" => ["*.gemspec"],
            "find" => 'spec\.required_ruby_version\s*=.*',
            "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
            "groups" => ["processor"],
          },
        },
      ))

      command = Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
        "dry_run" => true,
      )

      command.apply_patches(repo_name, repo_dir, git_repo)
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
      expect(git_repo.ls_files).to be_empty
    end

    it "is a no-op when the config has no patches: block" do
      command = build_command(nil)
      expect { command.apply_patches(repo_name, repo_dir, git_repo) }
        .not_to raise_error
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end
  end

  describe "resolve_source (metanorma/ci#347 Option B — visibility-conditional docker.yml)" do
    let(:repo) do
      Cimas::Repository.new(
        "mn-samples-bsi",
        "remote" => "ssh://git@github.com/metanorma/mn-samples-bsi",
        "branch" => "main",
        "files" => {},
      )
    end

    let(:command) { Cimas::Cli::Command.new(options("msg")) }

    it "returns a String source unchanged (legacy path stays the fast path)" do
      expect(command.resolve_source("gh-actions/samples/public-docker.yml", repo))
        .to eq("gh-actions/samples/public-docker.yml")
    end

    context "with a visibility-conditional Hash source" do
      let(:source) do
        {
          "if_public" => "gh-actions/samples/public-docker.yml",
          "if_private" => "gh-actions/samples/private-docker.yml.erb",
        }
      end

      it "picks the private template when the repo is private on GitHub" do
        allow(command).to receive(:repo_visibility_private?).with(repo).and_return(true)
        expect(command.resolve_source(source, repo))
          .to eq("gh-actions/samples/private-docker.yml.erb")
      end

      it "picks the public template when the repo is public on GitHub" do
        allow(command).to receive(:repo_visibility_private?).with(repo).and_return(false)
        expect(command.resolve_source(source, repo))
          .to eq("gh-actions/samples/public-docker.yml")
      end
    end

    it "raises when the Hash source is missing either required key" do
      allow(command).to receive(:repo_visibility_private?).with(repo).and_return(false)
      expect { command.resolve_source({ "if_public" => "x" }, repo) }
        .to raise_error(/visibility-conditional source needs/)
      expect { command.resolve_source({ "if_private" => "x" }, repo) }
        .to raise_error(/visibility-conditional source needs/)
    end

    it "caches the visibility lookup across multiple resolves on the same repo" do
      call_count = 0
      allow(command).to receive(:fetch_repo_visibility) do
        call_count += 1
        true
      end
      source = {
        "if_public" => "gh-actions/samples/public-docker.yml",
        "if_private" => "gh-actions/samples/private-docker.yml.erb",
      }
      3.times { command.resolve_source(source, repo) }
      expect(call_count).to eq(1)
    end
  end

  def config_file_path
    Cimas.root_path.join("spec/fixtures/sample.yml")
  end

  describe "scope guard for remote-mutating commands" do
    # push validates its required flags eagerly at execute; specs that
    # get past validation must supply them.
    PUSH_REQUIRED_OPTIONS = {
      "push_to_branch" => "wave-branch",
      "commit_message" => "msg",
    }.freeze

    let(:tmp_root) { Dir.mktmpdir("cimas-scope-spec") }

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(with_groups: false, config_groups: nil, settings_groups: nil, extra: {})
      config = {
        "repositories" => {
          "repo-a" => { "remote" => "git@github.com:org/repo-a.git", "branch" => "main", "files" => {} },
          "repo-b" => { "remote" => "git@github.com:org/repo-b.git", "branch" => "main", "files" => {} },
        },
      }
      config["groups"] = config_groups if config_groups
      config["groups"] ||= { "data" => %w[repo-a repo-b] } if with_groups
      config["settings"] = { "groups" => settings_groups } if settings_groups
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(config))

      Cimas::Cli::Command.new({
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
      }.merge(extra))
    end

    it "refuses push without -g because it would target every repository" do
      command = build_command

      expect { command.execute("push") }
        .to raise_error(OptionParser::MissingArgument, /would target all 2 repositories/)
    end

    it "refuses open-prs without -g before touching the GitHub API" do
      command = build_command

      expect { command.execute("open-prs") }
        .to raise_error(OptionParser::MissingArgument, /no -g given/)
    end

    it "refuses cleanup-merged-prs without -g" do
      command = build_command

      expect { command.execute("cleanup-merged-prs") }
        .to raise_error(OptionParser::MissingArgument, /cleanup-merged-prs: no -g given/)
    end

    it "refuses cleanup-closed-prs without -g" do
      command = build_command

      expect { command.execute("cleanup-closed-prs") }
        .to raise_error(OptionParser::MissingArgument, /cleanup-closed-prs: no -g given/)
    end

    it "refuses for-each without -g (arbitrary shell has push-scale blast radius)" do
      command = build_command

      expect { command.execute("for-each") }
        .to raise_error(OptionParser::MissingArgument, /for-each: no -g given/)
    end

    it "refuses an empty -g (e.g. `-g ''`) instead of silently doing nothing" do
      command = build_command(with_groups: true, extra: { "groups" => [] })

      expect { command.execute("push") }
        .to raise_error(OptionParser::InvalidArgument, /-g given but empty/)
    end

    it "refuses a -g group that resolves to zero repositories" do
      command = build_command(
        with_groups: true,
        config_groups: { "empty" => [] },
        extra: { "groups" => ["empty"] },
      )

      expect { command.execute("push") }
        .to raise_error(OptionParser::InvalidArgument, /resolves to 0 repositories/)
    end

    it "leaves cleanup-orphan-files unguarded without --push-after (local-only)" do
      command = build_command

      expect { command.execute("cleanup-orphan-files") }
        .not_to raise_error
    end

    it "guards cleanup-orphan-files when --push-after makes it remote-mutating" do
      command = build_command(extra: { "cleanup_push_after" => true })

      expect { command.execute("cleanup-orphan-files") }
        .to raise_error(OptionParser::MissingArgument, /cleanup-orphan-files: no -g given/)
    end

    it "leaves local-only commands unguarded without -g" do
      command = build_command

      expect { command.execute("diff") }
        .not_to raise_error
    end

    it "treats groups from cimas.yml settings as deliberate scope (no CLI -g needed)" do
      command = build_command(
        with_groups: true,
        settings_groups: ["data"],
        extra: PUSH_REQUIRED_OPTIONS,
      )

      expect { command.execute("push") }
        .to output(/Scope for push: 2 repo\(s\): repo-a, repo-b/).to_stdout
    end

    it "runs push scoped to a group and announces the scope" do
      command = build_command(
        with_groups: true,
        extra: { "groups" => ["data"] }.merge(PUSH_REQUIRED_OPTIONS),
      )

      expect { command.execute("push") }
        .to output(/Scope for push: 2 repo\(s\): repo-a, repo-b/).to_stdout
    end

    it "allows a single repo name as the group" do
      command = build_command(
        with_groups: true,
        extra: { "groups" => ["repo-a"] }.merge(PUSH_REQUIRED_OPTIONS),
      )

      expect { command.execute("push") }
        .to output(/Scope for push: 1 repo\(s\): repo-a/).to_stdout
    end

    it "announces the scope for cleanup commands too (uniform blast-radius line)" do
      command = build_command(with_groups: true, extra: { "groups" => ["repo-a"] })

      # cleanup-closed-prs requires no other flags: it announces, then
      # fails at the GitHub client — proving the announcement happens
      # before any GitHub interaction.
      expect { command.execute("cleanup-closed-prs") }
        .to output(/Scope for cleanup-closed-prs: 1 repo\(s\): repo-a/).to_stdout
        .and raise_error(/GITHUB_TOKEN/)
    end

    it "collapses the scope list past the announcement limit" do
      repos = (1..31).each_with_object({}) do |i, acc|
        acc["repo-#{i}"] = { "remote" => "git@github.com:org/repo-#{i}.git",
                             "branch" => "main", "files" => {} }
      end
      config = { "repositories" => repos }
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(config))

      command = Cimas::Cli::Command.new({
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
        "groups" => ["all"],
      }.merge(PUSH_REQUIRED_OPTIONS))

      expect { command.execute("push") }
        .to output(/Scope for push: 31 repo\(s\): \(list omitted, >30 repos\)/).to_stdout
    end
  end

  describe "required-option fail-fast (COMMANDS registry)" do
    let(:tmp_root) { Dir.mktmpdir("cimas-required-spec") }

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(extra = {})
      config = {
        "repositories" => {
          "repo-a" => { "remote" => "git@github.com:org/repo-a.git", "branch" => "main", "files" => {} },
        },
        "groups" => { "data" => ["repo-a"] },
      }
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(config))

      Cimas::Cli::Command.new({
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
        "groups" => ["data"],
      }.merge(extra))
    end

    it "fails fast on push without -b/-m, before any repo iteration" do
      command = build_command

      expect { command.execute("push") }
        .to raise_error(OptionParser::MissingArgument,
                        /push: missing required option\(s\): -b\/--push-branch, -m\/--message/)
    end

    it "fails fast on for-each without -c (previously exited 0 with no clones)" do
      command = build_command

      expect { command.execute("for-each") }
        .to raise_error(OptionParser::MissingArgument, /-c\/--shell-cmd/)
    end

    it "fails fast on release-preflight without --repo" do
      command = build_command

      expect { command.execute("release-preflight") }
        .to raise_error(OptionParser::MissingArgument, /missing required option\(s\): --repo/)
    end

    it "requires -b/-m on cleanup-orphan-files only under --push-after" do
      expect { build_command("cleanup_push_after" => true).execute("cleanup-orphan-files") }
        .to raise_error(OptionParser::MissingArgument, /-b\/--push-branch, -m\/--message/)

      # Local-only mode needs neither: validation passes; the loop just
      # skips the missing clone.
      expect { build_command.execute("cleanup-orphan-files") }
        .not_to raise_error
    end
  end

  describe ".remote_mutating? and COMMANDS registry" do
    it "classifies remote-mutating commands" do
      expect(Cimas::Cli::Command.remote_mutating?("push", {})).to be(true)
      expect(Cimas::Cli::Command.remote_mutating?("for-each", {})).to be(true)
      expect(Cimas::Cli::Command.remote_mutating?("cleanup-closed-prs", {})).to be(true)
    end

    it "leaves local commands unclassified" do
      expect(Cimas::Cli::Command.remote_mutating?("sync", {})).to be(false)
      expect(Cimas::Cli::Command.remote_mutating?("diff", {})).to be(false)
      expect(Cimas::Cli::Command.remote_mutating?("unknown", {})).to be(false)
    end

    it "treats cleanup-orphan-files as remote-mutating only under --push-after" do
      expect(Cimas::Cli::Command.remote_mutating?("cleanup-orphan-files", {})).to be(false)
      expect(Cimas::Cli::Command.remote_mutating?("cleanup-orphan-files",
                                                  "cleanup_push_after" => true)).to be(true)
    end
  end

  describe "config validation at initialize" do
    let(:tmp_root) { Dir.mktmpdir("cimas-config-spec") }

    after { FileUtils.rm_rf(tmp_root) }

    it "raises a clear error when the config has no repositories: section" do
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump("settings" => { "dry_run" => true }))

      expect do
        Cimas::Cli::Command.new(
          "config_file_path" => Pathname.new(config_path),
          "repos_path" => Pathname.new(tmp_root),
        )
      end.to raise_error(/no `repositories:` section/)
    end

    it "raises the same error for an empty config file" do
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, "")

      expect do
        Cimas::Cli::Command.new(
          "config_file_path" => Pathname.new(config_path),
          "repos_path" => Pathname.new(tmp_root),
        )
      end.to raise_error(/no `repositories:` section/)
    end
  end

  describe "for_each failure propagation" do
    let(:tmp_root) { Dir.mktmpdir("cimas-foreach-spec") }

    before do
      repo_dir = File.join(tmp_root, "repo-a")
      FileUtils.mkdir_p(repo_dir)
      Git.init(repo_dir)

      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(
        "repositories" => {
          "repo-a" => { "remote" => "git@github.com:org/repo-a.git", "branch" => "main", "files" => {} },
        },
        "groups" => { "data" => ["repo-a"] },
      ))
    end

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(shell_cmd)
      Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(File.join(tmp_root, "cimas.yml")),
        "repos_path" => Pathname.new(tmp_root),
        "groups" => ["data"],
        "shell_cmd" => shell_cmd,
      )
    end

    it "stays quiet when every command succeeds" do
      expect { build_command("true").for_each }.not_to raise_error
    end

    it "reports failures and raises after the sweep when a command fails" do
      expect { build_command("false").for_each }
        .to output(/\[ERROR\] 'false' failed in repo-a/).to_stdout
        .and raise_error(/failed in 1 repo\(s\): repo-a/)
    end
  end

  describe "filtered_repo_names" do
    let(:tmp_root) { Dir.mktmpdir("cimas-groups-spec") }

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(repositories:, groups: nil, config_groups: nil)
      config = { "repositories" => repositories }
      config["groups"] = config_groups if config_groups
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(config))

      options = {
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
      }
      options["groups"] = groups unless groups.nil?
      Cimas::Cli::Command.new(options)
    end

    def repo(name)
      { "remote" => "git@github.com:org/#{name}.git", "branch" => "main", "files" => {} }
    end

    it "returns every repository name when no -g is given" do
      command = build_command(repositories: { "repo-a" => repo("repo-a"), "repo-b" => repo("repo-b") })

      expect(command.filtered_repo_names).to eq(%w[repo-a repo-b])
    end

    it "expands a configured group to its member repositories" do
      command = build_command(
        repositories: { "repo-a" => repo("repo-a"), "repo-b" => repo("repo-b") },
        config_groups: { "data" => %w[repo-a repo-b] },
        groups: ["data"],
      )

      expect(command.filtered_repo_names).to eq(%w[repo-a repo-b])
    end

    it "does not crash when cimas.yml has no groups: section and -g names a repo" do
      command = build_command(repositories: { "repo-a" => repo("repo-a") }, groups: ["repo-a"])

      expect(command.filtered_repo_names).to eq(["repo-a"])
    end

    it "treats an unknown group name as a single repo name" do
      command = build_command(
        repositories: { "repo-a" => repo("repo-a") },
        config_groups: { "data" => ["repo-a"] },
        groups: ["typo-grp"],
      )

      expect(command.filtered_repo_names).to eq(["typo-grp"])
    end
  end

  describe "repo_by_name" do
    it "returns nil for a name not present in cimas.yml" do
      command = Cimas::Cli::Command.new(options("msg"))

      expect(command.repo_by_name("invalid-repo-name")).to be_nil
    end

    it "builds a Repository for a configured name" do
      command = Cimas::Cli::Command.new(options("msg"))

      repo = command.repo_by_name("metanorma-cli")

      expect(repo).to be_a(Cimas::Repository)
      expect(repo.name).to eq("metanorma-cli")
    end
  end

  describe "git_remote_to_github_name" do
    let(:command) { Cimas::Cli::Command.new(options("msg")) }

    it "maps the ssh:// URL form" do
      expect(command.git_remote_to_github_name("ssh://git@github.com/metanorma/foo"))
        .to eq("metanorma/foo")
    end

    it "maps the git@ scp form and strips a .git suffix" do
      expect(command.git_remote_to_github_name("git@github.com:metanorma/foo.git"))
        .to eq("metanorma/foo")
    end

    it "maps the https form and strips a .git suffix" do
      expect(command.git_remote_to_github_name("https://github.com/metanorma/foo.git"))
        .to eq("metanorma/foo")
    end

    it "raises a clear error for non-GitHub remotes instead of nil-crashing later" do
      expect { command.git_remote_to_github_name("git@gitlab.com:org/repo.git") }
        .to raise_error(/not a GitHub remote/)
    end
  end

  describe "managed file writing (header SSOT)" do
    let(:tmp_root) { Dir.mktmpdir("cimas-write-spec") }

    after { FileUtils.rm_rf(tmp_root) }

    let(:command) { Cimas::Cli::Command.new(options("msg")) }

    it "prefixes the generated header verbatim on copied files" do
      source = File.join(tmp_root, "source.yml")
      File.write(source, "body: 1\n")
      target = File.join(tmp_root, "nested", "dir", "target.yml")

      command.send(:copy_file, source, target)

      expect(File.read(target)).to eq(
        "# Auto-generated by Cimas: Do not edit it manually!\n" \
        "# See https://github.com/metanorma/cimas\n" \
        "body: 1\n"
      )
    end

    it "writes rendered templates through the same header" do
      target = File.join(tmp_root, "target.yml")

      command.send(:write_rendered, "rendered\n", target)

      expect(File.read(target)).to eq(
        "# Auto-generated by Cimas: Do not edit it manually!\n" \
        "# See https://github.com/metanorma/cimas\n" \
        "rendered\n"
      )
    end
  end

  describe "wd_has_drift?" do
    let(:tmp_root) { Dir.mktmpdir("cimas-drift-spec") }
    let(:repo_dir) { File.join(tmp_root, "repo") }

    before { FileUtils.mkdir_p(repo_dir); Git.init(repo_dir) }
    after { FileUtils.rm_rf(tmp_root) }

    let(:command) { Cimas::Cli::Command.new(options("msg")) }

    it "is false on a clean working copy and true once a file changes" do
      expect(command.wd_has_drift?(repo_dir)).to be(false)

      File.write(File.join(repo_dir, "Gemfile"), "source 'https://rubygems.org'")

      expect(command.wd_has_drift?(repo_dir)).to be(true)
    end

    it "is false for a directory that is not a git repo" do
      plain_dir = File.join(tmp_root, "plain")
      FileUtils.mkdir_p(plain_dir)

      expect(command.wd_has_drift?(plain_dir)).to be(false)
    end
  end

  def options(commit_message)
    {
      'config_file_path' => config_file_path,
      'repos_path' => Pathname.new(Dir.tmpdir),
      'commit_message' => commit_message,
    }
  end
end
