require "spec_helper"
require "fileutils"
require "tmpdir"

RSpec.describe Cimas::Repository do
  context "commit message must include request-checks" do
    it "add request-checks: true if missing" do
      command = Cimas::Cli::Command.new(options("Some commit message"))

      expect(command.commit_message).equal? "Some commit message\n\nrequest-checks: true"
    end

    it "don't modify message if request-checks: is passed" do
      command = Cimas::Cli::Command.new(options("Some commit message\n\nrequest-checks: false"))

      expect(command.commit_message).equal? "Some commit message\n\nrequest-checks: false"
    end
  end

  describe "apply_patches" do
    let(:tmp_root) { Dir.mktmpdir("cimas-patches-spec") }
    let(:repo_name) { "metanorma-cli" }
    let(:repo_dir) { File.join(tmp_root, repo_name) }
    let(:gemspec_path) { File.join(repo_dir, "foo.gemspec") }
    let(:git_double) { double("git", add: nil) }

    before do
      FileUtils.mkdir_p(repo_dir)
      File.write(gemspec_path, <<~GEMSPEC)
        Gem::Specification.new do |spec|
          spec.name = "foo"
          spec.required_ruby_version = Gem::Requirement.new(">= 2.7.0")
        end
      GEMSPEC
    end

    after { FileUtils.rm_rf(tmp_root) }

    def build_command(patches_block)
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(
        "repositories" => {
          repo_name => {
            "remote" => "ssh://git@github.com/metanorma/#{repo_name}",
            "branch" => "main",
            "files" => {},
          },
        },
        "groups" => {
          "processor" => [repo_name],
        },
        "patches" => patches_block,
      ))

      Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
      )
    end

    it "rewrites matching lines without prepending the auto-generated header" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["processor"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_double)
      content = File.read(gemspec_path)

      expect(content).to include('>= 3.1.0')
      expect(content).not_to include('>= 2.7.0')
      expect(content).not_to include('Auto-generated by Cimas')
    end

    it "stages the patched file via git.add with a repo-relative path" do
      expect(git_double).to receive(:add).with("foo.gemspec")

      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["processor"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_double)
    end

    it "warns and leaves the file untouched when the find pattern does not match" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'this_will_never_match',
          "replace" => 'irrelevant',
          "groups" => ["processor"],
        },
      )

      expect { command.apply_patches(repo_name, repo_dir, git_double) }
        .to output(/pattern did not match/).to_stdout

      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end

    it "warns when the glob matches no files" do
      command = build_command(
        "nonexistent" => {
          "files" => ["*.nope"],
          "find" => 'foo',
          "replace" => 'bar',
          "groups" => ["processor"],
        },
      )

      expect { command.apply_patches(repo_name, repo_dir, git_double) }
        .to output(/no files matched glob/).to_stdout
    end

    it "skips repos that are not in any of the patch's groups" do
      command = build_command(
        "ruby_version" => {
          "files" => ["*.gemspec"],
          "find" => 'spec\.required_ruby_version\s*=.*',
          "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
          "groups" => ["model"],
        },
      )

      command.apply_patches(repo_name, repo_dir, git_double)
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end

    it "does not write the file in dry-run mode" do
      config_path = File.join(tmp_root, "cimas.yml")
      File.write(config_path, YAML.dump(
        "repositories" => {
          repo_name => {
            "remote" => "ssh://git@github.com/metanorma/#{repo_name}",
            "branch" => "main",
            "files" => {},
          },
        },
        "groups" => { "processor" => [repo_name] },
        "patches" => {
          "ruby_version" => {
            "files" => ["*.gemspec"],
            "find" => 'spec\.required_ruby_version\s*=.*',
            "replace" => 'spec.required_ruby_version = Gem::Requirement.new(">= 3.1.0")',
            "groups" => ["processor"],
          },
        },
      ))

      command = Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(config_path),
        "repos_path" => Pathname.new(tmp_root),
        "dry_run" => true,
      )

      command.apply_patches(repo_name, repo_dir, git_double)
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end

    it "is a no-op when the config has no patches: block" do
      command = build_command(nil)
      expect { command.apply_patches(repo_name, repo_dir, git_double) }
        .not_to raise_error
      expect(File.read(gemspec_path)).to include('>= 2.7.0')
    end
  end

  describe "find_orphan_cimas_files" do
    let(:tmp_root) { Dir.mktmpdir("cimas-orphan-spec") }
    let(:repo_dir) { File.join(tmp_root, "repo") }

    before { FileUtils.mkdir_p(repo_dir) }
    after  { FileUtils.rm_rf(tmp_root) }

    def build_command
      Cimas::Cli::Command.new(
        "config_file_path" => Pathname.new(config_file_path),
        "repos_path" => Pathname.new(tmp_root),
      )
    end

    def write(rel, body)
      full = File.join(repo_dir, rel)
      FileUtils.mkdir_p(File.dirname(full))
      File.write(full, body)
      full
    end

    let(:cimas_header) do
      "# Auto-generated by Cimas: Do not edit it manually!\n" \
      "# See https://github.com/metanorma/cimas\n"
    end

    it "flags cimas-headered files that aren't in the mapping" do
      write(".github/workflows/docker.yml", cimas_header + "name: docker\n")
      write(".github/workflows/generate.yml", cimas_header + "name: generate\n")
      write(".rubocop.yml", cimas_header + "AllCops:\n")

      mapped = Set.new([".github/workflows/docker.yml", ".rubocop.yml"])
      orphans = build_command.find_orphan_cimas_files(repo_dir, mapped)

      expect(orphans).to contain_exactly(".github/workflows/generate.yml")
    end

    it "ignores files without the cimas header (custom CI, sources)" do
      write(".github/workflows/custom.yml", "name: custom\n# not cimas-managed\n")
      write("README.md", "# Sources\nNot a cimas file.\n")

      orphans = build_command.find_orphan_cimas_files(repo_dir, Set.new)

      expect(orphans).to be_empty
    end

    it "ignores files under .git/" do
      # Simulate a git object file that happens to contain the marker text
      # (extremely unlikely but the walk must skip .git/ regardless).
      FileUtils.mkdir_p(File.join(repo_dir, ".git", "objects"))
      write(".git/objects/decoy", cimas_header + "not a real cimas file\n")

      orphans = build_command.find_orphan_cimas_files(repo_dir, Set.new)

      expect(orphans).to be_empty
    end

    it "returns [] on a clean repo (all mapped files present, no orphans)" do
      write(".github/workflows/docker.yml", cimas_header)
      write(".rubocop.yml", cimas_header)

      mapped = Set.new([".github/workflows/docker.yml", ".rubocop.yml"])
      orphans = build_command.find_orphan_cimas_files(repo_dir, mapped)

      expect(orphans).to eq([])
    end

    it "handles non-UTF-8 (binary) files by skipping them" do
      # PNG-ish magic bytes; File.read with encoding: 'UTF-8' would tag
      # the string as UTF-8 but the header check is a plain include? on
      # the string, so binary content just doesn't contain the marker
      # substring. The important invariant is: no exception, no false
      # positive.
      File.binwrite(File.join(repo_dir, "image.png"), "\x89PNG\r\n\x1a\n".b + ("\x00" * 100))

      expect { build_command.find_orphan_cimas_files(repo_dir, Set.new) }
        .not_to raise_error
    end
  end

  def config_file_path
    Cimas.root_path.join("spec/fixtures/sample.yml")
  end

  def options(commit_message)
    {
      'config_file_path' => config_file_path,
      'repos_path' => Pathname.new(Dir.tmpdir),
      'commit_message' => commit_message,
    }
  end
end
