require "spec_helper"
require "fileutils"
require "tmpdir"
require "yaml"
require "git"

RSpec.describe "GitHub-backed commands (offline fake client)" do
  let(:root) { Dir.mktmpdir("cimas-gh-spec") }
  let(:repos_path) { File.join(root, "repos") }
  let(:repo_dir) { File.join(repos_path, "repo-a") }
  let(:fake) { FakeGitHubClient.new }
  let(:github) { Cimas::GitHub.new(client: fake) }

  before do
    FileUtils.mkdir_p(repo_dir)
    git = Git.init(repo_dir)
    git.config("user.name", "Spec")
    git.config("user.email", "spec@example.com")
    File.write(File.join(repo_dir, "README.md"), "hi\n")
    git.add("README.md")
    git.commit("init")

    File.write(File.join(root, "cimas.yml"), YAML.dump(
      "repositories" => {
        "repo-a" => {
          "remote" => "ssh://git@github.com/org/repo-a",
          "branch" => "main",
          "files" => {},
        },
      },
      "groups" => { "data" => ["repo-a"] },
    ))
  end

  after { FileUtils.rm_rf(root) }

  def build(extra = {})
    Cimas::Cli::Command.new({
      "config_file_path" => Pathname.new(File.join(root, "cimas.yml")),
      "repos_path" => Pathname.new(repos_path),
      "groups" => ["repo-a"],
      "github" => github,
      "github_token" => "unused-when-injected",
      "cooldown_count" => 1000,
      "cooldown_time" => 0,
    }.merge(extra))
  end

  describe "open_prs" do
    let(:base) do
      {
        "merge_branch" => "wave-1",
        "pr_message" => "wave title",
        "assignees" => "alice",
        "reviewers" => "bot-user,bob",
      }
    end

    it "creates a PR, labels automerge, requests reviews, assigns" do
      cmd = build(base)

      expect { cmd.execute("open-prs") }
        .to output(/PR org\/repo-a#11 created/).to_stdout

      create = fake.calls_named(:create_pull_request).first
      expect(create[1..5]).to eq(
        ["org/repo-a", "main", "wave-1", "wave title", "As title. \n\n _Generated by Cimas_."],
      )
      expect(fake.calls_named(:add_labels_to_an_issue).first[3]).to eq(["automerge"])
      # bot-user stripped from reviewers (self-review)
      expect(fake.calls_named(:request_pull_request_review).first[3]).to eq(["bob"])
      expect(fake.calls_named(:add_assignees).first[3]).to eq(["alice"])
    end

    it "skips when a PR already exists" do
      fake.create_error = FakeGitHubClient::Error.new("A pull request already exists for wave-1")
      cmd = build(base)

      expect { cmd.execute("open-prs") }
        .to output(/PR already exists for wave-1/).to_stdout
    end

    it "skips when the wave branch is missing on the remote" do
      fake.create_error = FakeGitHubClient::Error.new(
        "Validation Failed\nfield: head\ncode: invalid",
      )
      cmd = build(base)

      expect { cmd.execute("open-prs") }
        .to output(/Branch wave-1 does not exist/).to_stdout
    end

    it "supersedes stale open cimas-sync PRs without closing them" do
      stale = fake.seed_pull_request(
        "org/repo-a",
        number: 3,
        head: FakeGitHubClient::Head.new(ref: "cimas-sync-old"),
        state: "open",
      )
      cmd = build(base.merge("supersede_stale" => true))

      expect { cmd.execute("open-prs") }
        .to output(/superseded org\/repo-a#3/).to_stdout

      labels = fake.calls_named(:add_labels_to_an_issue)
      expect(labels.map { |c| c[3] }).to include(["superseded-by-#12"])
      expect(fake.calls_named(:close_pull_request)).to be_empty
      create_body = fake.calls_named(:create_pull_request).first[5]
      expect(create_body).to include("Supersedes #3")
      expect(stale.state).to eq("open")
    end

    it "flattens stale PRs when --flatten-stale is set" do
      fake.seed_pull_request(
        "org/repo-a",
        number: 4,
        head: FakeGitHubClient::Head.new(ref: "cimas-sync-old"),
        state: "open",
      )
      cmd = build(base.merge("flatten_stale" => true, "supersede_stale" => true))

      expect { cmd.execute("open-prs") }
        .to output(/flattened org\/repo-a#4/).to_stdout

      expect(fake.calls_named(:close_pull_request).map { |c| c[2] }).to eq([4])
      labels = fake.calls_named(:add_labels_to_an_issue).map { |c| c[3] }
      expect(labels).to include(["superseded-closed-by-#12"])
    end
  end

  describe "cleanup_merged_prs" do
    it "deletes the branch when the PR is merged" do
      fake.seed_pull_request(
        "org/repo-a",
        number: 5,
        head: FakeGitHubClient::Head.new(ref: "wave-1"),
        state: "closed",
        merged_at: Time.now,
      )
      cmd = build("push_to_branch" => "wave-1")

      expect { cmd.execute("cleanup-merged-prs") }
        .to output(/\[deleted\] org\/repo-a:wave-1/).to_stdout

      expect(fake.deleted_branches).to include(["org/repo-a", "wave-1"])
    end

    it "skips open PRs" do
      fake.seed_pull_request(
        "org/repo-a",
        number: 6,
        head: FakeGitHubClient::Head.new(ref: "wave-1"),
        state: "open",
      )
      cmd = build("push_to_branch" => "wave-1")

      expect { cmd.execute("cleanup-merged-prs") }
        .to output(/\[skip-open\] org\/repo-a:wave-1/).to_stdout
      expect(fake.deleted_branches).to be_empty
    end

    it "deletes the branch when no PR exists" do
      cmd = build("push_to_branch" => "wave-orphan")

      expect { cmd.execute("cleanup-merged-prs") }
        .to output(/\[deleted\] org\/repo-a:wave-orphan \(no PR found\)/).to_stdout
      expect(fake.deleted_branches).to include(["org/repo-a", "wave-orphan"])
    end
  end

  describe "cleanup_closed_prs" do
    it "deletes closed-not-merged branches matching the prefix" do
      fake.seed_pull_request(
        "org/repo-a",
        number: 7,
        head: FakeGitHubClient::Head.new(ref: "cimas-sync-2026-01-01"),
        state: "closed",
        merged_at: nil,
        closed_at: Time.now,
      )
      # merged PR with same prefix — must not be deleted
      fake.seed_pull_request(
        "org/repo-a",
        number: 8,
        head: FakeGitHubClient::Head.new(ref: "cimas-sync-merged"),
        state: "closed",
        merged_at: Time.now,
      )
      cmd = build

      expect { cmd.execute("cleanup-closed-prs") }
        .to output(/\[deleted\] org\/repo-a:cimas-sync-2026-01-01/).to_stdout

      expect(fake.deleted_branches).to eq([["org/repo-a", "cimas-sync-2026-01-01"]])
    end
  end
end
