require "spec_helper"
require "fileutils"
require "tmpdir"

RSpec.describe Cimas::OrphanFiles do
  let(:tmp_root) { Dir.mktmpdir("cimas-orphan-spec") }
  let(:repo_dir) { File.join(tmp_root, "repo") }

  before { FileUtils.mkdir_p(repo_dir) }
  after  { FileUtils.rm_rf(tmp_root) }

  def write(rel, body)
    full = File.join(repo_dir, rel)
    FileUtils.mkdir_p(File.dirname(full))
    File.write(full, body)
    full
  end

  let(:cimas_header) do
    "# Auto-generated by Cimas: Do not edit it manually!\n" \
    "# See https://github.com/metanorma/cimas\n"
  end

  it "flags cimas-headered files that aren't in the mapping" do
    write(".github/workflows/docker.yml", cimas_header + "name: docker\n")
    write(".github/workflows/generate.yml", cimas_header + "name: generate\n")
    write(".rubocop.yml", cimas_header + "AllCops:\n")

    mapped = Set.new([".github/workflows/docker.yml", ".rubocop.yml"])
    orphans = described_class.find(repo_dir, mapped)

    expect(orphans).to contain_exactly(".github/workflows/generate.yml")
  end

  it "ignores files without the cimas header (custom CI, sources)" do
    write(".github/workflows/custom.yml", "name: custom\n# not cimas-managed\n")
    write("README.md", "# Sources\nNot a cimas file.\n")

    orphans = described_class.find(repo_dir, Set.new)

    expect(orphans).to be_empty
  end

  it "ignores files under .git/" do
    # Simulate a git object file that happens to contain the marker text
    # (extremely unlikely but the walk must skip .git/ regardless).
    FileUtils.mkdir_p(File.join(repo_dir, ".git", "objects"))
    write(".git/objects/decoy", cimas_header + "not a real cimas file\n")

    orphans = described_class.find(repo_dir, Set.new)

    expect(orphans).to be_empty
  end

  it "returns [] on a clean repo (all mapped files present, no orphans)" do
    write(".github/workflows/docker.yml", cimas_header)
    write(".rubocop.yml", cimas_header)

    mapped = Set.new([".github/workflows/docker.yml", ".rubocop.yml"])
    orphans = described_class.find(repo_dir, mapped)

    expect(orphans).to eq([])
  end

  it "handles non-UTF-8 (binary) files by skipping them" do
    File.binwrite(File.join(repo_dir, "image.png"), "\x89PNG\r\n\x1a\n".b + ("\x00" * 100))

    expect { described_class.find(repo_dir, Set.new) }
      .not_to raise_error
  end

  it "narrows the sweep to only_targets when given" do
    write(".github/workflows/generate.yml", cimas_header + "name: generate\n")
    write(".rubocop.yml", cimas_header + "AllCops:\n")

    orphans = described_class.find(repo_dir, Set.new,
                                   [".github/workflows/generate.yml"].to_set)

    expect(orphans).to contain_exactly(".github/workflows/generate.yml")
  end
end
