require "spec_helper"
require "fileutils"
require "tmpdir"
require "yaml"
require "open3"
require "git"

# End-to-end coverage of the wave money path — sync renders templates
# into clones, diff reports drift, push provisions the wave branch and
# lands it on a remote — entirely offline: the "remote" is a local bare
# repository. Exercises dispatch → COMMANDS registry → iterators →
# managed-file writer → WorkingCopy → git.
RSpec.describe "wave lifecycle (offline)" do
  let(:root) { Dir.mktmpdir("cimas-lifecycle") }
  let(:origin) { File.join(root, "origin.git") }
  let(:repos_path) { File.join(root, "repos") }
  let(:master_path) { File.join(root, "master") }
  let(:repo_dir) { File.join(repos_path, "repo-a") }

  before do
    FileUtils.mkdir_p(repos_path)
    system("git", "init", "--bare", "--initial-branch", "main", origin,
           out: File::NULL, err: File::NULL)
    git = Git.clone(origin, "repo-a", path: repos_path)
    git.config("user.name", "Spec")
    git.config("user.email", "spec@example.com")
    File.write(File.join(repo_dir, "README.md"), "# repo-a\n")
    git.add("README.md")
    git.commit("init")
    git.push("origin", "main")

    FileUtils.mkdir_p(master_path)
    File.write(File.join(master_path, "rake.yml"), "name: rake\n")
    File.write(File.join(master_path, "docker.yml.erb"), "flavor: <%= flavor %>\n")

    File.write(File.join(root, "cimas.yml"), YAML.dump(
      "repositories" => {
        "repo-a" => {
          "remote" => origin,
          "branch" => "main",
          "files" => {
            ".github/workflows/rake.yml" => "rake.yml",
            ".github/workflows/docker.yml" => "docker.yml.erb",
          },
          "template" => { "binding" => { "flavor" => "iso" } },
        },
      },
      "groups" => { "data" => ["repo-a"] },
    ))
  end

  after { FileUtils.rm_rf(root) }

  def command(extra = {})
    Cimas::Cli::Command.new({
      "config_file_path" => Pathname.new(File.join(root, "cimas.yml")),
      "repos_path" => Pathname.new(repos_path),
      "config_master_path" => Pathname.new(master_path),
      "groups" => ["repo-a"],
    }.merge(extra))
  end

  def read_in_repo(rel)
    File.read(File.join(repo_dir, rel))
  end

  it "sync → diff → push lands the rendered wave on the remote branch" do
    cmd = command("push_to_branch" => "wave-1", "commit_message" => "sync wave")

    expect { cmd.execute("sync") }
      .to output(/Syncing and staging files in repo-a/).to_stdout

    # Copied file carries the generated header; ERB file renders the
    # repo's template binding.
    expect(read_in_repo(".github/workflows/rake.yml"))
      .to start_with("# Auto-generated by Cimas: Do not edit it manually!")
    expect(read_in_repo(".github/workflows/docker.yml")).to include("flavor: iso")

    expect { cmd.execute("diff") }
      .to output(/DIFF FOR repo-a/).to_stdout

    expect { cmd.execute("push") }
      .to output(/Committing on repo-a/).to_stdout

    bare = Git.bare(origin)
    expect(bare.is_branch?("wave-1")).to be(true)
    expect(bare.gcommit("wave-1").message).to include("sync wave")
    expect(bare.gcommit("wave-1").message).to include("request-checks: true")
    %w[.github/workflows/rake.yml .github/workflows/docker.yml].each do |path|
      _out, _err, status = Open3.capture3("git", "--git-dir", origin,
                                          "cat-file", "-e", "wave-1:#{path}")
      expect(status).to be_success, "expected #{path} on the wave branch"
    end
  end

  it "skips the push as a no-op when there is no drift" do
    cmd = command("push_to_branch" => "wave-1", "commit_message" => "sync wave")
    cmd.execute("sync")
    cmd.execute("push")

    expect { cmd.execute("push") }
      .to output(/Skipping no-op push to repo-a \(no drift\)/).to_stdout
  end

  it "applies patches during sync and stages the result" do
    File.write(File.join(root, "cimas.yml"), YAML.dump(
      "repositories" => {
        "repo-a" => {
          "remote" => origin,
          "branch" => "main",
          "files" => {
            ".github/workflows/rake.yml" => "rake.yml",
          },
        },
      },
      "groups" => { "data" => ["repo-a"] },
      "patches" => {
        "stamp" => {
          "files" => ["README.md"],
          "find" => "# repo-a",
          "replace" => "# repo-a (cimas-managed)",
          "groups" => ["data"],
        },
      },
    ))

    command.execute("sync")

    expect(read_in_repo("README.md")).to include("# repo-a (cimas-managed)")
  end
end
