require "pathname"

module Cimas
  # Ownership marker cimas writes into every file it generates and
  # detects when deciding whether a file is cimas-managed (orphan
  # cleanup). One definition — sync and cleanup must agree on it.
  GENERATED_HEADER_MARKER = "Auto-generated by Cimas"
  GENERATED_HEADER = [
    "# #{GENERATED_HEADER_MARKER}: Do not edit it manually!",
    "# See https://github.com/metanorma/cimas",
  ].join("\n").freeze

  # Autoload paths are absolute (resolved from __dir__) so a plain
  # `require_relative` boot from exe/cimas works from any cwd, without
  # $LOAD_PATH setup.
  autoload :VERSION, File.expand_path("cimas/version", __dir__)
  autoload :Repository, File.expand_path("cimas/repository", __dir__)
  autoload :Patch, File.expand_path("cimas/patch", __dir__)
  autoload :OrphanFiles, File.expand_path("cimas/orphan_files", __dir__)
  autoload :Cli, File.expand_path("cimas/cli", __dir__)

  def self.root
    File.dirname(__dir__)
  end

  def self.root_path
    Pathname.new(Cimas.root)
  end
end
